name: Esteira de testes
run-name: ${{ github.actor }} is testing out 🚀
on:
  push:
    branches:
      - 'feature**'
      - 'develop'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
  Execute_Unit_Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Unit Tests
        run: mvn test
  Execute_Integrations_Tests:
    needs: Execute_Unit_Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Integration Tests
        run: mvn verify
  Code_Coverage_Report:
    needs: Execute_Integrations_Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: JaCoCo Test Report
        run: mvn jacoco:report
